version: '3.8'
services:
  be:
    build: ./BE
    ports:
      - "3001:3001"
    volumes:
        - ./BE:/app
  fe:
    build: ./FE
    ports:
      - "3000:3000"
    volumes:
        - ./FE:/app
        - /app/node_modules
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"


networks:
  network:
    driver: bridge